config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  devise_for :users
  root to: "comic_trips#home"

  resources :comic_trips, path: 'comics', only: [:index, :show, :new, :create ]
  resources :bookmarks, only: []
  get "profile", to: "pages#profile"
  get "edit", to: "pages#edit"
  get "qrcode", to: "pages#qrcode"
  get "news", to: "pages#news"

  resources :compositions, only: []
  resources :elements, only: []
  resources :vignettes, only: []

  resources :album_comic_trips, only: []
  resources :albums, only: []
end

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-info">
  <img src="https://res.cloudinary.com/dlmpwvjpw/image/upload/v1709649745/ComixBnB/comix_trip_logo_staple_euqeny.png" alt="Comixtrip Logo">
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="toggling" data-controller="toggle">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dlmpwvjpw/image/upload/v1709649745/ComixBnB/comix_trip_logo_staple_euqeny.png" %>
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>

            <li class="nickname active mt-1">
              <%= "#{current_user.nickname}" %>
            </li>
            <li class="nav-item dropdown">
              <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag current_user.avatar.presence || 'default_avatar.png', class: "avatar", alt: "dropdown menu" %>
              </a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Create something", new_comic_trip_path, class: "dropdown-item" %>
                <%= link_to "Profile", profile_path, class: "dropdown-item" %>
                <%= link_to "Share it", qrcode_path, class: "dropdown-item" %>
                <%= link_to "News", news_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
  <%= link_to new_comic_trip_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dlmpwvjpw/image/upload/v1710429005/CREATE_nqecih.png" %>
      <% end %>


          <% else %>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: "nav-link navbar-brand" do %>
              <%= image_tag "https://res.cloudinary.com/dlmpwvjpw/image/upload/v1709720639/Comix_Trip_Nav_Button_Square_luhrk4.png", alt: "Login" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-8 my-3 d-none" data-toggle-target="togglableElement">
      <%= form_with url: root_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Type a keyword"%>
        <%= submit_tag "Search", name: "", class: "btn btn-dark" %>
      <% end %>
    </div>
  </div>
 </div>
</div>

app/views/shared/_search.html.erb
<% if controller_name == "comic_trips" && action_name.in?(%w[home index]) %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="row justify-content-center">
        <div class="col-sm-8 my-3" data-toggle-target="togglableElement">
          <%= form_with url: comic_trips_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :query,
                  params[:query],
                  class: "form-control",
                  placeholder: "Search a comiXtrip"
            %>
            <%= submit_tag "Search", name: "", class: "btn btn-success" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>